name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Create artifact directory
        run: mkdir -p artifact && cp build/libs/zs-assignments-1.0-SNAPSHOT.jar artifact/application.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: artifact/application.jar

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "artifact/application.jar"
          target: "/home/${{ secrets.USERNAME }}"
          strip_components: 1

      - name: Execute remote SSH commands
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/${{ secrets.USERNAME }}/app
            cd /home/${{ secrets.USERNAME }}/app
            # Create properties file from secrets
            echo "${{ secrets.APPLICATION_PROPERTIES }}" > application.properties
            kill $(cat app.pid) 2>/dev/null || true
            mv /home/${{ secrets.USERNAME }}/application.jar app.jar
            nohup java -jar app.jar > app.log 2>&1 &
            echo $! > app.pid